### ISSUE TITLE
Bank Overview while away from city

### ISSUE THREAD

**Issue by dozack** [ElvUI-Cataclysm/ElvUI_Enhanced-4.3.4#6]
Hello,
is it posible to add an ability to view my bank overview while I am away from city? I found it very useful while using addon Bagnon so i miss it in ElvUI. Maybe i just did not find the right button and this ability is already there. 
Thanks for any advice.

**Comment by Crumdidlyumshis** [comment]
This feature will probably not be added. However, you can use Bagnon and if there isn’t a skin available for it we can add one. :)
